site_name: MVC Calculator

theme:
  name: readthedocs
  custom_dir: overrides
  logo: img/icn_emg.png

# Homepage redirects to user-guide
nav:
  - User Guide: user-guide.md
  - License Information: license.md
  - Troubleshooting Guide: troubleshooting.md
  - File Formats: file-formats.md
  - Keyboard Shortcuts: keyboard-shortcuts.md

extra_css:
  - css/extra.css

extra_javascript:
  - js/lightbox.js

extra:
  generator: false

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - codehilite

  - toc:
      permalink: true
      toc_depth: 6

  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.emoji












# site_name: MVC Calculator

# theme:
  # name: readthedocs
  # custom_dir: overrides
  # logo: img/icn_emg.png

# nav:  
  # - Home: index.md 

# extra_css:
  # - css/extra.css

# extra:
  # generator: false

# plugins:
  # - search

# markdown_extensions:
  # - admonition
  # - codehilite
  # - toc:
      # permalink: true
  # - tables
  # - pymdownx.details
  # - pymdownx.superfences















# # site_name: MVC Calculator

# # theme:
  # # name: readthedocs
  # # custom_dir: overrides
  # # logo: img/icn_emg.png

# # extra_css: 
  # # - css/extra.css

# # extra:
  # # generator: false

# # # plugins:
  # # # - search
  # # # - bibtex:   
      # # # bib_file: "docs/bibs/IMM_DRUMMER.bib"
      # # # csl_file: "docs/bibs/apa-6th-edition.csl"
      # # # # cite_inline: true  
      # # # # cite_style: author_year            
      # # # # reference_style: plain
      # # # # reference_heading: References      

# # plugins:
  # # - macros
  # # - search
  # # - bibtex:
      # # bib_file: docs/bibs/IMM_DRUMMER.bib
      # # csl_file: docs/bibs/apa-6th-edition.csl
      # # cite_inline: true                # ðŸ‘ˆ renders (Author, Year)
      # # render_bibliography: true        # ðŸ‘ˆ creates the References section
      # # reference_heading: References    # ðŸ‘ˆ section title
      # # full_bibliography: false         # ðŸ‘ˆ only show cited entries


# # markdown_extensions:
  # # - admonition
  # # - codehilite
  # # - toc:
      # # permalink: true
  # # - tables
  # # # - footnotes                            # ðŸ‘ˆ required for reference anchors
  # # - pymdownx.details                     # ðŸ‘ˆ helps with ::: blocks
  # # - pymdownx.superfences                 # ðŸ‘ˆ improves ::: bibliography rendering
  
  
# # # nav:
# # # - QUICK START:
  # # # - MetaSensors: metasensors.md
# # # - SENSORS:
  # # # - MetaMotionRL (MMRL): metamotionrl.md
  # # # - MetaMotionS (MMS): metamotions.md
# # # - APPS:
  # # # - MetaBase App: metabse.md
  # # # - MetaWear App: metawear.md
# # # - HUB:
  # # # - MetaHub: metahub.md
# # # - DEVELOPER APIS:
  # # # - MetaWear APIs: metawear_api.md
  # # # - C++ APIs: cpp_api.md
  # # # - Java APIs: java_api.md
  # # # - Swift APIs: swift_api.md
  # # # - Python APIs: python_api.md
  # # # - JavaScript APIs: js_api.md